[package]
name = "logq"
description = "A web-server log file command line toolkit with SQL interface"
repository = "https://github.com/MnO2/logq"
version = "0.1.0"
license = "MIT"
authors = ["Paul Meng <me@paulme.ng>"]
readme = "README.md"
keywords = ["log", "sql", "query", "search"]
categories = ["command-line-utilities"]
edition = "2018"
exclude = ["/benches/**", "/.travis.yml", "/data/**"]

[dependencies]
clap = {version = "2.33.0", features = ["yaml"]}
regex = "1.1.7"
failure = "0.1.5"
hashbrown = "0.5"
ordered-float = "1.0"
nom = "5.0"
prettytable-rs = "^0.8"
chrono = "0.4"
url = "2.1.0"
csv = "1.1"
lazy_static = "1.3.0"
json = "0.11.15"
