[package]
name = "logq"
version = "0.1.0"
authors = ["Paul Meng <me@paulme.ng>"]
edition = "2018"

[dependencies]
clap = {version = "2.33.0", features = ["yaml"]}
regex = "1.1.7"
failure = "0.1.5"
hashbrown = "0.5"
ordered-float = "1.0"
nom = "5.0"
prettytable-rs = "^0.8"
chrono = "0.4"
url = "2.1.0"
csv = "1.1"
lazy_static = "1.3.0"